T-gnus 6.14.6; synch up with Gnus v5.8.8.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -19,6 +19,8 @@ ac_help="$ac_help
   --with-lispdir=DIR      Where to install lisp files
                           (for XEmacs package, use --with-packagedir instead)"
 ac_help="$ac_help
+  --with-w3=DIR           Specify where to find the w3 package"
+ac_help="$ac_help
   --with-packagedir=DIR   package DIR for XEmacs"
 ac_help="$ac_help
   --with-addpath=PATH     search Emacs-Lisp libraries with PATH
@@ -533,9 +535,18 @@ else
 fi
 
 
-  GNUS_PRODUCT_NAME=t-gnus
+echo $ac_n "defining gnus product name... $ac_c"
+  if eval "test \"\${EMACS_cv_GNUS_PRODUCT_NAME+set}\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  EMACS_cv_GNUS_PRODUCT_NAME=t-gnus
+fi
+
+  GNUS_PRODUCT_NAME=${EMACS_cv_GNUS_PRODUCT_NAME}
+  echo "$ac_t""${GNUS_PRODUCT_NAME}" 1>&6
+  
 echo $ac_n "checking whether ${MAKE-make} sets \${MAKE}""... $ac_c" 1>&6
-echo "configure:539: checking whether ${MAKE-make} sets \${MAKE}" >&5
+echo "configure:550: checking whether ${MAKE-make} sets \${MAKE}" >&5
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y%./+-%__p_%'`
 if eval "test \"\${ac_cv_prog_make_${ac_make}_set+set}\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -592,7 +603,7 @@ ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 # SVR4 /usr/ucb/install, which tries to use the nonexistent group "staff"
 # ./install, which can be erroneously created by make from ./install.sh.
 echo $ac_n "checking for a BSD compatible install""... $ac_c" 1>&6
-echo "configure:596: checking for a BSD compatible install" >&5
+echo "configure:607: checking for a BSD compatible install" >&5
 if test -z "$INSTALL"; then
 if eval "test \"\${ac_cv_path_install+set}\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -651,7 +662,7 @@ test -z "$INSTALL_DATA" && INSTALL_DATA='${INSTALL} -m 644'
 # Extract the first word of "makeinfo", so it can be a program name with args.
 set dummy makeinfo; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:655: checking for $ac_word" >&5
+echo "configure:666: checking for $ac_word" >&5
 if eval "test \"\${ac_cv_prog_MAKEINFO+set}\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -681,6 +692,8 @@ fi
 
       test x$EMACS = xt && EMACS=
 
+    unset ac_cv_prog_EMACS; unset ac_cv_prog_XEMACS;
+
   # Check whether --with-emacs or --without-emacs was given.
 if test "${with_emacs+set}" = set; then
   withval="$with_emacs"
@@ -690,7 +703,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:694: checking for $ac_word" >&5
+echo "configure:707: checking for $ac_word" >&5
 if eval "test \"\${ac_cv_prog_EMACS+set}\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -724,7 +737,7 @@ test -n "$EMACS" || EMACS="emacs"
       # Extract the first word of "$withval", so it can be a program name with args.
 set dummy $withval; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:728: checking for $ac_word" >&5
+echo "configure:741: checking for $ac_word" >&5
 if eval "test \"\${ac_cv_prog_EMACS+set}\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -761,7 +774,7 @@ if test "${with_xemacs+set}" = set; then
       # Extract the first word of "xemacs", so it can be a program name with args.
 set dummy xemacs; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:765: checking for $ac_word" >&5
+echo "configure:778: checking for $ac_word" >&5
 if eval "test \"\${ac_cv_prog_XEMACS+set}\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -792,7 +805,7 @@ fi
       # Extract the first word of "$withval", so it can be a program name with args.
 set dummy $withval; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:796: checking for $ac_word" >&5
+echo "configure:809: checking for $ac_word" >&5
 if eval "test \"\${ac_cv_prog_XEMACS+set}\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -829,7 +842,7 @@ do
 # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:833: checking for $ac_word" >&5
+echo "configure:846: checking for $ac_word" >&5
 if eval "test \"\${ac_cv_prog_EMACS+set}\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -863,65 +876,317 @@ fi
 
   
   
-  echo $ac_n "checking where lisp files should go""... $ac_c" 1>&6
-echo "configure:868: checking where lisp files should go" >&5
+
+  echo $ac_n "checking what a flavor does $EMACS have""... $ac_c" 1>&6
+echo "configure:882: checking what a flavor does $EMACS have" >&5
+
+    unset EMACS_cv_SYS_flavor;
+
+  
+elisp="(cond ((featurep (quote xemacs)) \"XEmacs\")\
+          ((boundp (quote MULE)) \"MULE\")\
+          (t \"FSF Emacs\"))"
+if test -z ""noecho""; then
+	echo $ac_n "checking for flavor""... $ac_c" 1>&6
+echo "configure:892: checking for flavor" >&5
+fi
+if eval "test \"\${EMACS_cv_SYS_flavor+set}\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  
+	OUTPUT=./conftest-$$
+	echo ${EMACS}' -batch -eval '\''(let ((x '${elisp}')) (write-region (if (stringp x) (princ x) (prin1-to-string x)) nil "'${OUTPUT}'" nil 5))'\' >& 5 2>&1
+	eval ${EMACS}' -batch -eval '\''(let ((x '${elisp}')) (write-region (if (stringp x) (princ x) (prin1-to-string x)) nil "'${OUTPUT}'" nil 5))'\' >& 5 2>&1
+	retval=`cat ${OUTPUT}`
+	echo "=> ${retval}" >& 5 2>&1
+	rm -f ${OUTPUT}
+	EMACS_cv_SYS_flavor=$retval
+
+fi
+
+flavor=${EMACS_cv_SYS_flavor}
+if test -z ""noecho""; then
+	echo "$ac_t""$flavor" 1>&6
+fi
+
+  case $EMACS_cv_SYS_flavor in
+  XEmacs)
+    EMACS_FLAVOR=xemacs;;
+  MULE)
+    EMACS_FLAVOR=mule;;
+  *)
+    EMACS_FLAVOR=emacs;;
+  esac
+  echo "$ac_t""$EMACS_cv_SYS_flavor" 1>&6
+  if test "$prefix" = "NONE"; then
+	echo $ac_n "checking prefix for your Emacs""... $ac_c" 1>&6
+echo "configure:924: checking prefix for your Emacs" >&5
+	
+elisp="(expand-file-name \"..\" invocation-directory)"
+if test -z ""noecho""; then
+	echo $ac_n "checking for prefix""... $ac_c" 1>&6
+echo "configure:929: checking for prefix" >&5
+fi
+if eval "test \"\${EMACS_cv_SYS_prefix+set}\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  
+	OUTPUT=./conftest-$$
+	echo ${EMACS}' -batch -eval '\''(let ((x '${elisp}')) (write-region (if (stringp x) (princ x) (prin1-to-string x)) nil "'${OUTPUT}'" nil 5))'\' >& 5 2>&1
+	eval ${EMACS}' -batch -eval '\''(let ((x '${elisp}')) (write-region (if (stringp x) (princ x) (prin1-to-string x)) nil "'${OUTPUT}'" nil 5))'\' >& 5 2>&1
+	retval=`cat ${OUTPUT}`
+	echo "=> ${retval}" >& 5 2>&1
+	rm -f ${OUTPUT}
+	EMACS_cv_SYS_prefix=$retval
+
+fi
+
+prefix=${EMACS_cv_SYS_prefix}
+if test -z ""noecho""; then
+	echo "$ac_t""$prefix" 1>&6
+fi
+
+	prefix=${EMACS_cv_SYS_prefix}
+	echo "$ac_t""$prefix" 1>&6
+  fi
   # Check whether --with-lispdir or --without-lispdir was given.
 if test "${with_lispdir+set}" = set; then
   withval="$with_lispdir"
-  lispdir=$withval
-else
-  emacsdir=$datadir/emacs
-    test x$prefix = xNONE && prefix=$ac_default_prefix
-    case `echo x$EMACS | sed -e 's/x//' -e 's/^.*\///'` in
-    emacs|emacs-*)
-      if test -d $prefix/share/emacs; then
-        emacsdir=$prefix/share/emacs
-      elif test -d $prefix/lib/emacs; then
-        emacsdir=$prefix/lib/emacs
-      fi;;
-    xemacs|xemacs-*)
-      if test -d $prefix/lib/xemacs; then
-        emacsdir=$prefix/lib/xemacs
-      elif test -d $prefix/share/xemacs; then
-        emacsdir=$prefix/share/xemacs
-      fi;;
-    mule|mule-*)
-      if test -d $prefix/share/mule; then
-        emacsdir=$prefix/share/mule
-      elif test -d $prefix/lib/mule; then
-        emacsdir=$prefix/lib/mule
-      elif test -d $prefix/share/emacs; then
-        emacsdir=$prefix/share/emacs
-      elif test -d $prefix/lib/emacs; then
-        emacsdir=$prefix/lib/emacs
-      fi;;
-    esac
-    lispdir=$emacsdir/site-lisp/$GNUS_PRODUCT_NAME
+  lispdir=${withval}
 fi
 
-  echo "$ac_t""$lispdir
+  echo $ac_n "checking where lisp files should go""... $ac_c" 1>&6
+echo "configure:960: checking where lisp files should go" >&5
+  if test -z "$lispdir"; then
+        theprefix=$prefix
+    if test "x$theprefix" = "xNONE"; then
+	theprefix=$ac_default_prefix
+    fi
+    lispdir="\$(datadir)/${EMACS_FLAVOR}/site-lisp/${GNUS_PRODUCT_NAME}"
+    for thedir in share lib; do
+	potential=
+	if test -d ${theprefix}/${thedir}/${EMACS_FLAVOR}/site-lisp; then
+	   lispdir="\$(prefix)/${thedir}/${EMACS_FLAVOR}/site-lisp/${GNUS_PRODUCT_NAME}"
+	   break
+	fi
+    done
+  fi
+  if test ${EMACS_FLAVOR} = xemacs; then
+    echo "$ac_t""$lispdir
          (it will be ignored when \"make install-package[-ja]\" is done)" 1>&6
+  else
+    echo "$ac_t""$lispdir" 1>&6
+  fi
   
-  # Check whether --with-packagedir or --without-packagedir was given.
+
+
+echo $ac_n "checking for acceptable W3 version""... $ac_c" 1>&6
+echo "configure:985: checking for acceptable W3 version" >&5
+
+unset EMACS_cv_ACCEPTABLE_W3;
+unset EMACS_cv_SYS_w3_dir;
+unset EMACS_cv_SYS_w3_forms;
+
+if eval "test \"\${EMACS_cv_ACCEPTABLE_W3+set}\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  
+
+if test -z ""noecho""; then
+	echo $ac_n "checking for w3-form-encode-xwfu in w3_forms""... $ac_c" 1>&6
+echo "configure:998: checking for w3-form-encode-xwfu in w3_forms" >&5
+fi
+library=`echo w3_forms | tr _ -`
+
+elisp="(progn (fmakunbound (quote w3-form-encode-xwfu)) (condition-case nil (progn (require (quote $library)) (fboundp (quote w3-form-encode-xwfu))) (error (prog1 nil (message \"$library not found\")))))"
+if test -z ""noecho""; then
+	echo $ac_n "checking for w3_forms""... $ac_c" 1>&6
+echo "configure:1005: checking for w3_forms" >&5
+fi
+if eval "test \"\${EMACS_cv_SYS_w3_forms+set}\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  
+	OUTPUT=./conftest-$$
+	echo ${EMACS}' -batch -eval '\''(let ((x '${elisp}')) (write-region (if (stringp x) (princ x) (prin1-to-string x)) nil "'${OUTPUT}'" nil 5))'\' >& 5 2>&1
+	eval ${EMACS}' -batch -eval '\''(let ((x '${elisp}')) (write-region (if (stringp x) (princ x) (prin1-to-string x)) nil "'${OUTPUT}'" nil 5))'\' >& 5 2>&1
+	retval=`cat ${OUTPUT}`
+	echo "=> ${retval}" >& 5 2>&1
+	rm -f ${OUTPUT}
+	EMACS_cv_SYS_w3_forms=$retval
+
+fi
+
+w3_forms=${EMACS_cv_SYS_w3_forms}
+if test -z ""noecho""; then
+	echo "$ac_t""$w3_forms" 1>&6
+fi
+
+if test "${EMACS_cv_SYS_w3_forms}" = "nil"; then
+	EMACS_cv_SYS_w3_forms=no
+fi
+if test "${EMACS_cv_SYS_w3_forms}" = "t"; then
+	EMACS_cv_SYS_w3_forms=yes
+fi
+HAVE_w3_forms=${EMACS_cv_SYS_w3_forms}
+
+if test -z ""noecho""; then
+	echo "$ac_t""$HAVE_w3_forms" 1>&6
+fi
+
+if test "${HAVE_w3_forms}" = "yes"; then
+	EMACS_cv_ACCEPTABLE_W3=yes
+else
+	EMACS_cv_ACCEPTABLE_W3=
+fi
+
+if test "x${EMACS_cv_ACCEPTABLE_W3}" = "xyes"; then
+	
+elisp="(file-name-directory (locate-library \"w3-forms\"))"
+if test -z ""noecho""; then
+	echo $ac_n "checking for w3_dir""... $ac_c" 1>&6
+echo "configure:1049: checking for w3_dir" >&5
+fi
+if eval "test \"\${EMACS_cv_SYS_w3_dir+set}\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  
+	OUTPUT=./conftest-$$
+	echo ${EMACS}' -batch -eval '\''(let ((x '${elisp}')) (write-region (if (stringp x) (princ x) (prin1-to-string x)) nil "'${OUTPUT}'" nil 5))'\' >& 5 2>&1
+	eval ${EMACS}' -batch -eval '\''(let ((x '${elisp}')) (write-region (if (stringp x) (princ x) (prin1-to-string x)) nil "'${OUTPUT}'" nil 5))'\' >& 5 2>&1
+	retval=`cat ${OUTPUT}`
+	echo "=> ${retval}" >& 5 2>&1
+	rm -f ${OUTPUT}
+	EMACS_cv_SYS_w3_dir=$retval
+
+fi
+
+w3_dir=${EMACS_cv_SYS_w3_dir}
+if test -z ""noecho""; then
+	echo "$ac_t""$w3_dir" 1>&6
+fi
+
+	EMACS_cv_ACCEPTABLE_W3=$EMACS_cv_SYS_w3_dir
+fi
+
+fi
+
+   # Check whether --with-w3 or --without-w3 was given.
+if test "${with_w3+set}" = set; then
+  withval="$with_w3"
+   EMACS_cv_ACCEPTABLE_W3=`( cd $withval && pwd || echo "$withval" ) 2> /dev/null` 
+fi
+
+   W3=${EMACS_cv_ACCEPTABLE_W3}
+   
+   if test "x${EMACS_cv_ACCEPTABLE_W3}" = "x"; then
+	echo "$ac_t""not found" 1>&6
+   else
+	echo "$ac_t""${W3}" 1>&6
+   fi
+
+  if test ${EMACS_FLAVOR} = xemacs; then
+    echo $ac_n "checking where the XEmacs package is""... $ac_c" 1>&6
+echo "configure:1091: checking where the XEmacs package is" >&5
+    # Check whether --with-packagedir or --without-packagedir was given.
 if test "${with_packagedir+set}" = set; then
   withval="$with_packagedir"
   if test x$withval != xyes -a x$withval != x; then
-      echo $ac_n "checking where the package should go""... $ac_c" 1>&6
-echo "configure:911: checking where the package should go" >&5
-      PACKAGEDIR=$withval
-      echo "$ac_t""$PACKAGEDIR" 1>&6
-    fi
+	PACKAGEDIR=$withval
+      else
+	  
+elisp="(let (package-dir)\
+      (if (boundp (quote early-packages))\
+	  (let ((dirs (delq nil (append (if early-package-load-path\
+					    early-packages)\
+					(if late-package-load-path\
+					    late-packages)\
+					(if last-package-load-path\
+					    last-packages)))))\
+	    (while (and dirs (not package-dir))\
+	      (if (file-directory-p (car dirs))\
+		  (setq package-dir (car dirs)\
+			dirs (cdr dirs))))))\
+      (or package-dir \"\"))"
+if test -z ""noecho""; then
+	echo $ac_n "checking for PACKAGEDIR""... $ac_c" 1>&6
+echo "configure:1114: checking for PACKAGEDIR" >&5
+fi
+if eval "test \"\${EMACS_cv_SYS_PACKAGEDIR+set}\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
 else
-  PACKAGEDIR=
+  
+	OUTPUT=./conftest-$$
+	echo ${EMACS}' -batch -eval '\''(let ((x '${elisp}')) (write-region (if (stringp x) (princ x) (prin1-to-string x)) nil "'${OUTPUT}'" nil 5))'\' >& 5 2>&1
+	eval ${EMACS}' -batch -eval '\''(let ((x '${elisp}')) (write-region (if (stringp x) (princ x) (prin1-to-string x)) nil "'${OUTPUT}'" nil 5))'\' >& 5 2>&1
+	retval=`cat ${OUTPUT}`
+	echo "=> ${retval}" >& 5 2>&1
+	rm -f ${OUTPUT}
+	EMACS_cv_SYS_PACKAGEDIR=$retval
+
 fi
 
+PACKAGEDIR=${EMACS_cv_SYS_PACKAGEDIR}
+if test -z ""noecho""; then
+	echo "$ac_t""$PACKAGEDIR" 1>&6
+fi
+
+      fi
+else
+    
+elisp="(let (package-dir)\
+      (if (boundp (quote early-packages))\
+	  (let ((dirs (delq nil (append (if early-package-load-path\
+					    early-packages)\
+					(if late-package-load-path\
+					    late-packages)\
+					(if last-package-load-path\
+					    last-packages)))))\
+	    (while (and dirs (not package-dir))\
+	      (if (file-directory-p (car dirs))\
+		  (setq package-dir (car dirs)\
+			dirs (cdr dirs))))))\
+      (or package-dir \"\"))"
+if test -z ""noecho""; then
+	echo $ac_n "checking for PACKAGEDIR""... $ac_c" 1>&6
+echo "configure:1153: checking for PACKAGEDIR" >&5
+fi
+if eval "test \"\${EMACS_cv_SYS_PACKAGEDIR+set}\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  
+	OUTPUT=./conftest-$$
+	echo ${EMACS}' -batch -eval '\''(let ((x '${elisp}')) (write-region (if (stringp x) (princ x) (prin1-to-string x)) nil "'${OUTPUT}'" nil 5))'\' >& 5 2>&1
+	eval ${EMACS}' -batch -eval '\''(let ((x '${elisp}')) (write-region (if (stringp x) (princ x) (prin1-to-string x)) nil "'${OUTPUT}'" nil 5))'\' >& 5 2>&1
+	retval=`cat ${OUTPUT}`
+	echo "=> ${retval}" >& 5 2>&1
+	rm -f ${OUTPUT}
+	EMACS_cv_SYS_PACKAGEDIR=$retval
+
+fi
+
+PACKAGEDIR=${EMACS_cv_SYS_PACKAGEDIR}
+if test -z ""noecho""; then
+	echo "$ac_t""$PACKAGEDIR" 1>&6
+fi
+
+fi
+
+    if test x$PACKAGEDIR = x; then
+      echo "$ac_t""not found" 1>&6
+    else
+      echo "$ac_t""$PACKAGEDIR" 1>&6
+    fi
+  else
+    PACKAGEDIR=
+  fi
   
   # Check whether --with-addpath or --without-addpath was given.
 if test "${with_addpath+set}" = set; then
   withval="$with_addpath"
   if test x$withval != xyes -a x$withval != x; then
       echo $ac_n "checking where to find the additional elisp libraries""... $ac_c" 1>&6
-echo "configure:925: checking where to find the additional elisp libraries" >&5
+echo "configure:1190: checking where to find the additional elisp libraries" >&5
       ADDITIONAL_LOAD_PATH=$withval
       echo "$ac_t""$ADDITIONAL_LOAD_PATH" 1>&6
     fi
@@ -1075,6 +1340,7 @@ s%@includedir@%$includedir%g
 s%@oldincludedir@%$oldincludedir%g
 s%@infodir@%$infodir%g
 s%@mandir@%$mandir%g
+s%@GNUS_PRODUCT_NAME@%$GNUS_PRODUCT_NAME%g
 s%@SET_MAKE@%$SET_MAKE%g
 s%@INSTALL_PROGRAM@%$INSTALL_PROGRAM%g
 s%@INSTALL_SCRIPT@%$INSTALL_SCRIPT%g
@@ -1083,6 +1349,8 @@ s%@MAKEINFO@%$MAKEINFO%g
 s%@EMACS@%$EMACS%g
 s%@XEMACS@%$XEMACS%g
 s%@lispdir@%$lispdir%g
+s%@HAVE_w3_forms@%$HAVE_w3_forms%g
+s%@W3@%$W3%g
 s%@PACKAGEDIR@%$PACKAGEDIR%g
 s%@ADDITIONAL_LOAD_PATH@%$ADDITIONAL_LOAD_PATH%g
 
